### ISSUE TITLE
What are your top five all time favourite Rap albums?

### ISSUE THREAD

**Issue by mischah** [kahlil/ama#1]
Mine are:
1. I …
2. E …
3. T …
4. M …
5. D …

**Comment by khalillechelt** [comment]
Here is the list of the 5 rap albums that influenced me immensely in the late nineties.

## 5: [Wu-Tang Clan - Enter The Wu-Tang (36 Chambers)](https://en.wikipedia.org/wiki/Enter_the_Wu-Tang_%2836_Chambers%29)

This was the Wu-Tang album that was a staple in the tape deck of the cars me and my friends were driving around in. Always on repeat.

## 4: [NTM - Suprême NTM](http://www.amazon.de/Supreme-NTM-Supr%C3%AAme/dp/B001UQI3AW?tag=duc02-21)

Hardcore rap from Paris. The mixture of really amazing production with the very different deliveries of the two MCs was  just amazing. When rehearsing with my own group back then I sometimes imitated Joey Starr's Dancehall-influenced rap style which amused my friends tremendously.

## 3: [Cypress Hill - Black Sunday](http://www.amazon.de/Black-Sunday-Explicit-Cypress-Hill/dp/B001SOQ0A6/ref=tmm_msc_swatch_0?_encoding=UTF8&qid=&sr=)

What can I say? Those tracks were mesmerizing to me (completely without smoking. I never smoked). Rolling bassline with B-Real's awesome voice and flow on top! Best.

## 2: [Saïan Supa Crew - X Raisons](https://www.youtube.com/watch?v=Ppwn37XY6WQ)

Really dope beats, very diverse array of voices in the crew with eclectic rap styles that mix in singing and Dancehall style deejaying as well. 

## 1: [IAM – L'école Du Micro D'argent](https://www.youtube.com/watch?v=VHmaDk_26KI&list=PLC5F9BD58E487DE2D)

Very mysterious style, a real classic by now. IAM from Marseille have influenced a lot of european musicians. 

That's my list. What do those letters in your list mean?

**Comment by mischah** [comment]
Hej Kahlil,

thanks for the answers. I nice selection. Although I don’t feel french rap music because I don’t understand a single word :see_no_evil: … beside of the »IAM« album. Because it just was a banger.

> What do those letters in your list mean?

I just wrote the first letters of my top 5 because i didn’t want to influence you on this tough decision :stuck_out_tongue_winking_eye: 

So here is my list:
1. [Illmatic – Nas](https://www.youtube.com/watch?v=_srvHOu75vM)
2. [Enta Da Stage – Black Moon](https://www.youtube.com/watch?v=z6D4aPRjV6g)
3. [The Chronic – Dr. Dre](https://www.youtube.com/watch?v=YyMeweFrT_s)
4. [Midnight Marauders – A Tribe Called Quest](https://www.youtube.com/watch?v=aYOsU6GYMZw)
5. [Da Shinin – Smif ’n’ Wessun](https://www.youtube.com/watch?v=Jw5V2k_SMh0)

**Comment by khalillechelt** [comment]
Nice! I like Tribe and some of Dre's stuff. Nas I never got into but I respect your list :heart:!

tbqh I barely understand anything by the frenchies either but understanding the lyrics was never really that important to me. I always went by the feel of the track and the flow and the rhythm of the lyrics and the sound of the voice.

**Comment by mischah** [comment]
Your Right. Flow and voice are as important as the lyrics. Like Guru rapped once:

> It's mostly tha voice, that gets you up
> It's mostly tha voice, that makes you buck
> A lot of rappers got flavor, and some got skills
> But if your voice ain't dope then you need to [chill... chill... ]

:laughing:
