### ISSUE TITLE
One career or life advice for starters in the web dev world you wish you would have known back when you started out.

### ISSUE THREAD

**Issue by anselmh** [kahlil/ama#3]

**Comment by khalillechelt** [comment]
The world of web development is vast. I think it is crucial to find the area that you are most interested in and strongest at and then go all in on that. 

Find it by trying a lot of things. 

By going all in on it I mean read everything about it, write code and surround yourself with people from whom you can learn. 

If you want to work at a company, find the companies that do the   best work in the area that you are interested in and find out what they care about. Try to get their attention in a creative and interesting way. 

Write and/or talk about what you learn.
