### ISSUE TITLE
What are your favorite movies?

### ISSUE THREAD

**Issue by robbbz** [kahlil/ama#6]

**Comment by khalillechelt** [comment]
## [Pulp Fiction](http://www.imdb.com/title/tt0110912/?ref_=nv_sr_1)

This was the first movie that really blew my mind. I think I ended up seeing it 7 times in the theaters when it came out. Tarantino's writing, the characters he created and the unconventional storytelling did it for me.

## [Desperado](http://www.imdb.com/title/tt0112851/?ref_=nv_sr_1)

I recorded this movie on VHS when I was still in high school and kept watching it over and over. I had my mom transcribe the song lyrics of the song that the Antonio Banderas sings in the beginning and taught it to myself. It was a hit on parties :smile:

## [La Haine](http://www.imdb.com/title/tt0113247/?ref_=nv_sr_1)

Beautifully shot, written and acted, all black and white, it shows a day in the life of a group of young men who live in the banlieue of Paris. Really good.

## [Fist of Legend](http://www.imdb.com/title/tt0110200/?ref_=nv_sr_1)

An early Jet Lee movie that impressed me immensely. I found it so interesting how every fight had a very different choreography and Jet's skills are just amazing. No Jet Lee movie after that had a similar impact on me. As soon as he made Hollywood movies it got less interesting.

## [The Jungle Book](http://www.imdb.com/title/tt0061852/?ref_=nv_sr_2)

Hands down the best music in a Disney movie ever and I just love the characters and the aesthetics. It's nice how you can still see that the animations were hand-drawn back then. Saw this as a kid and still love it :smile:
